---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-volume
spec:
  capacity:
    storage: '4Gi'
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: my-volume
  mountOptions:
    - hard
    - nfsvers=4.1
  nfd:
    path: /common/volume
    server: 172.17.0.2