---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rc-demo
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: team
        operator: In
        values:
          - dev
          - prod
          - test
      - key: team
        operator: NotIn
        values:
          - test
  template:
    metadata:
      name: re-demo
      labels:
        team: dev
    spec:
      containers:
        - name: rc-demo1
          image: nginx:1.7.1
          ports:
            - containerPort: 80