---
apiVersion: v1
kind: pod
metadata:
  name: hello-pod
  labels: 
    app: hello-pod
spec:
  container:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocal: TCP

