---
apiVersion: v1
kind: Pod
metadata:
  name: readiness-command-probe
spec:
  restartPolicy: Always
  containers:
    - name: ubuntu-container
      image: ubuntu:latest
      command:
        - /bin/bash
        - -ec
        - touch /tmp/ranga;sleep 30; rm /tmp/ranga;sleep 600
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/ranga
        initialDelaySeconds: 5
        periodSeconds: 5